import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "READLY_BOOKSTORE",
  description: "Generated by create next app",
  icons: { icon:"/Images/REDFAVICON.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
<Navbar/>
<main className="min-h-screen">
  {children}
</main>

      </body>
    </html>
  );
}
